import { ABIDataTypes, BitcoinAbiTypes, OP_NET_ABI } from 'opnet';

export const LendBTCEvents = [];

export const LendBTCAbi = [
    {
        name: '_deposit',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'sharesReceived', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_addCollateral',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'sharesReceived', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_withdrawCollateral',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_withdraw',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getDepositPosition',
        inputs: [
            { name: 'user', type: ABIDataTypes.ADDRESS },
            { name: 'token', type: ABIDataTypes.UINT8 },
        ],
        outputs: [
            { name: 'netDeposited', type: ABIDataTypes.UINT256 },
            { name: 'shares', type: ABIDataTypes.UINT256 },
            { name: 'tokenBalance', type: ABIDataTypes.UINT256 },
            { name: 'earnedInterest', type: ABIDataTypes.UINT256 },
            { name: 'currentAPR', type: ABIDataTypes.UINT256 },
            { name: 'estimatedAPY', type: ABIDataTypes.UINT256 },
            { name: 'historicalAPYBps', type: ABIDataTypes.UINT256 },
            { name: 'firstDepositBlock', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getAllDepositPositions',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'btcNetDeposited', type: ABIDataTypes.UINT256 },
            { name: 'btcShares', type: ABIDataTypes.UINT256 },
            { name: 'btcTokenBalance', type: ABIDataTypes.UINT256 },
            { name: 'btcEarned', type: ABIDataTypes.UINT256 },
            { name: 'btcCurrentAPR', type: ABIDataTypes.UINT256 },
            { name: 'btcEstimatedAPY', type: ABIDataTypes.UINT256 },
            { name: 'btcHistoricalAPY', type: ABIDataTypes.UINT256 },
            { name: 'btcDepositBlock', type: ABIDataTypes.UINT256 },
            { name: 'motoNetDeposited', type: ABIDataTypes.UINT256 },
            { name: 'motoShares', type: ABIDataTypes.UINT256 },
            { name: 'motoTokenBalance', type: ABIDataTypes.UINT256 },
            { name: 'motoEarned', type: ABIDataTypes.UINT256 },
            { name: 'motoCurrentAPR', type: ABIDataTypes.UINT256 },
            { name: 'motoEstimatedAPY', type: ABIDataTypes.UINT256 },
            { name: 'motoHistoricalAPY', type: ABIDataTypes.UINT256 },
            { name: 'motoDepositBlock', type: ABIDataTypes.UINT256 },
            { name: 'pillNetDeposited', type: ABIDataTypes.UINT256 },
            { name: 'pillShares', type: ABIDataTypes.UINT256 },
            { name: 'pillTokenBalance', type: ABIDataTypes.UINT256 },
            { name: 'pillEarned', type: ABIDataTypes.UINT256 },
            { name: 'pillCurrentAPR', type: ABIDataTypes.UINT256 },
            { name: 'pillEstimatedAPY', type: ABIDataTypes.UINT256 },
            { name: 'pillHistoricalAPY', type: ABIDataTypes.UINT256 },
            { name: 'pillDepositBlock', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getInterestRates',
        inputs: [{ name: 'token', type: ABIDataTypes.UINT8 }],
        outputs: [
            { name: 'borrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'supplyAPR', type: ABIDataTypes.UINT256 },
            { name: 'borrowAPY', type: ABIDataTypes.UINT256 },
            { name: 'supplyAPY', type: ABIDataTypes.UINT256 },
            { name: 'utilizationRate', type: ABIDataTypes.UINT256 },
            { name: 'totalDeposits', type: ABIDataTypes.UINT256 },
            { name: 'totalBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'availLiquidity', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getAllPoolRates',
        inputs: [],
        outputs: [
            { name: 'btcBorrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'btcSupplyAPR', type: ABIDataTypes.UINT256 },
            { name: 'btcBorrowAPY', type: ABIDataTypes.UINT256 },
            { name: 'btcSupplyAPY', type: ABIDataTypes.UINT256 },
            { name: 'btcUtilizationRate', type: ABIDataTypes.UINT256 },
            { name: 'btcTotalDeposits', type: ABIDataTypes.UINT256 },
            { name: 'btcTotalBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'btcAvailLiquidity', type: ABIDataTypes.UINT256 },
            { name: 'motoBorrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'motoSupplyAPR', type: ABIDataTypes.UINT256 },
            { name: 'motoBorrowAPY', type: ABIDataTypes.UINT256 },
            { name: 'motoSupplyAPY', type: ABIDataTypes.UINT256 },
            { name: 'motoUtilizationRate', type: ABIDataTypes.UINT256 },
            { name: 'motoTotalDeposits', type: ABIDataTypes.UINT256 },
            { name: 'motoTotalBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'motoAvailLiquidity', type: ABIDataTypes.UINT256 },
            { name: 'pillBorrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'pillSupplyAPR', type: ABIDataTypes.UINT256 },
            { name: 'pillBorrowAPY', type: ABIDataTypes.UINT256 },
            { name: 'pillSupplyAPY', type: ABIDataTypes.UINT256 },
            { name: 'pillUtilizationRate', type: ABIDataTypes.UINT256 },
            { name: 'pillTotalDeposits', type: ABIDataTypes.UINT256 },
            { name: 'pillTotalBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'pillAvailLiquidity', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getPoolInfo',
        inputs: [{ name: 'token', type: ABIDataTypes.UINT8 }],
        outputs: [
            { name: 'totalDeposits', type: ABIDataTypes.UINT256 },
            { name: 'totalBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'availableLiquidity', type: ABIDataTypes.UINT256 },
            { name: 'utilizationRate', type: ABIDataTypes.UINT256 },
            { name: 'interestRate', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getExchangeRate',
        inputs: [{ name: 'token', type: ABIDataTypes.UINT8 }],
        outputs: [{ name: 'exchangeRate', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_borrow',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'collateralValue', type: ABIDataTypes.UINT256 },
            { name: 'borrowValue', type: ABIDataTypes.UINT256 },
            { name: 'ltvAfterBorrow', type: ABIDataTypes.UINT256 },
            { name: 'healthFactorAfter', type: ABIDataTypes.UINT256 },
            { name: 'riskStatus', type: ABIDataTypes.UINT256 },
            { name: 'loyaltyDiscountBps', type: ABIDataTypes.UINT256 },
            { name: 'loyaltyTier', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_repay',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'actualRepaid', type: ABIDataTypes.UINT256 },
            { name: 'remainingDebt', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'riskStatus', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getBorrowPosition',
        inputs: [
            { name: 'user', type: ABIDataTypes.ADDRESS },
            { name: 'token', type: ABIDataTypes.UINT8 },
        ],
        outputs: [
            { name: 'userDebt', type: ABIDataTypes.UINT256 },
            { name: 'userCollateral', type: ABIDataTypes.UINT256 },
            { name: 'debtValueInSats', type: ABIDataTypes.UINT256 },
            { name: 'totalBorrowValueSats', type: ABIDataTypes.UINT256 },
            { name: 'loanToValueRatio', type: ABIDataTypes.UINT256 },
            { name: 'interestRate', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'maxBorrowable', type: ABIDataTypes.UINT256 },
            { name: 'isLiquidatable', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getAllBorrowPositions',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'btcDebt', type: ABIDataTypes.UINT256 },
            { name: 'btcCollateral', type: ABIDataTypes.UINT256 },
            { name: 'btcDebtValueSats', type: ABIDataTypes.UINT256 },
            { name: 'btcTotalBorrowSats', type: ABIDataTypes.UINT256 },
            { name: 'btcLTV', type: ABIDataTypes.UINT256 },
            { name: 'btcInterestRate', type: ABIDataTypes.UINT256 },
            { name: 'btcHealthFactor', type: ABIDataTypes.UINT256 },
            { name: 'btcMaxBorrowable', type: ABIDataTypes.UINT256 },
            { name: 'btcIsLiquidatable', type: ABIDataTypes.UINT256 },
            { name: 'motoDebt', type: ABIDataTypes.UINT256 },
            { name: 'motoCollateral', type: ABIDataTypes.UINT256 },
            { name: 'motoDebtValueSats', type: ABIDataTypes.UINT256 },
            { name: 'motoTotalBorrowSats', type: ABIDataTypes.UINT256 },
            { name: 'motoLTV', type: ABIDataTypes.UINT256 },
            { name: 'motoInterestRate', type: ABIDataTypes.UINT256 },
            { name: 'motoHealthFactor', type: ABIDataTypes.UINT256 },
            { name: 'motoMaxBorrowable', type: ABIDataTypes.UINT256 },
            { name: 'motoIsLiquidatable', type: ABIDataTypes.UINT256 },
            { name: 'pillDebt', type: ABIDataTypes.UINT256 },
            { name: 'pillCollateral', type: ABIDataTypes.UINT256 },
            { name: 'pillDebtValueSats', type: ABIDataTypes.UINT256 },
            { name: 'pillTotalBorrowSats', type: ABIDataTypes.UINT256 },
            { name: 'pillLTV', type: ABIDataTypes.UINT256 },
            { name: 'pillInterestRate', type: ABIDataTypes.UINT256 },
            { name: 'pillHealthFactor', type: ABIDataTypes.UINT256 },
            { name: 'pillMaxBorrowable', type: ABIDataTypes.UINT256 },
            { name: 'pillIsLiquidatable', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_previewBorrow',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'isAllowed', type: ABIDataTypes.UINT256 },
            { name: 'rejectReason', type: ABIDataTypes.UINT256 },
            { name: 'collateralValue', type: ABIDataTypes.UINT256 },
            { name: 'currentBorrowValue', type: ABIDataTypes.UINT256 },
            { name: 'newBorrowValue', type: ABIDataTypes.UINT256 },
            { name: 'newHealthFactor', type: ABIDataTypes.UINT256 },
            { name: 'newLTV', type: ABIDataTypes.UINT256 },
            { name: 'maxBorrowable', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_liquidate',
        inputs: [
            { name: 'borrower', type: ABIDataTypes.ADDRESS },
            { name: 'collateralToken', type: ABIDataTypes.UINT8 },
            { name: 'borrowToken', type: ABIDataTypes.UINT8 },
            { name: 'debtAmount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'collateralSeized', type: ABIDataTypes.UINT256 },
            { name: 'debtRepaid', type: ABIDataTypes.UINT256 },
            { name: 'liquidationBonus', type: ABIDataTypes.UINT256 },
            { name: 'borrowerHFAfter', type: ABIDataTypes.UINT256 },
            { name: 'borrowerRiskAfter', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getLiquidationInfo',
        inputs: [{ name: 'borrower', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'isLiquidatable', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'collateralValue', type: ABIDataTypes.UINT256 },
            { name: 'borrowValue', type: ABIDataTypes.UINT256 },
            { name: 'btcDebt', type: ABIDataTypes.UINT256 },
            { name: 'motoDebt', type: ABIDataTypes.UINT256 },
            { name: 'pillDebt', type: ABIDataTypes.UINT256 },
            { name: 'btcCollateral', type: ABIDataTypes.UINT256 },
            { name: 'motoCollateral', type: ABIDataTypes.UINT256 },
            { name: 'pillCollateral', type: ABIDataTypes.UINT256 },
            { name: 'maxLiquidatableBtc', type: ABIDataTypes.UINT256 },
            { name: 'maxLiquidatableMoto', type: ABIDataTypes.UINT256 },
            { name: 'maxLiquidatablePill', type: ABIDataTypes.UINT256 },
            { name: 'liquidationBonusBps', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_previewLiquidation',
        inputs: [
            { name: 'borrower', type: ABIDataTypes.ADDRESS },
            { name: 'collateralToken', type: ABIDataTypes.UINT8 },
            { name: 'borrowToken', type: ABIDataTypes.UINT8 },
            { name: 'debtAmount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'isAllowed', type: ABIDataTypes.UINT256 },
            { name: 'rejectReason', type: ABIDataTypes.UINT256 },
            { name: 'actualDebtRepaid', type: ABIDataTypes.UINT256 },
            { name: 'collatBase', type: ABIDataTypes.UINT256 },
            { name: 'bonusAmount', type: ABIDataTypes.UINT256 },
            { name: 'collateralSeized', type: ABIDataTypes.UINT256 },
            { name: 'borrowerHFAfter', type: ABIDataTypes.UINT256 },
            { name: 'borrowerRiskAfter', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_creditBtcDeposit',
        inputs: [
            { name: 'user', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'sharesReceived', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getUserVault',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'collateralValue', type: ABIDataTypes.UINT256 },
            { name: 'borrowValue', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getHealthFactor',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [{ name: 'healthFactor', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_setTokenAddresses',
        inputs: [
            { name: 'motoAddress', type: ABIDataTypes.ADDRESS },
            { name: 'pillAddress', type: ABIDataTypes.ADDRESS },
        ],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_setPrice',
        inputs: [
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'price', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_setPaused',
        inputs: [{ name: 'paused', type: ABIDataTypes.BOOL }],
        outputs: [{ name: 'success', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getLoyaltyInfo',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'motoBalance', type: ABIDataTypes.UINT256 },
            { name: 'loyaltyTier', type: ABIDataTypes.UINT256 },
            { name: 'discountBps', type: ABIDataTypes.UINT256 },
            { name: 'nextTierThreshold', type: ABIDataTypes.UINT256 },
            { name: 'nextTierDiscountBps', type: ABIDataTypes.UINT256 },
            { name: 'motoToNextTier', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getEffectiveBorrowRate',
        inputs: [{ name: 'token', type: ABIDataTypes.UINT8 }],
        outputs: [
            { name: 'baseBorrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'effectiveBorrowAPR', type: ABIDataTypes.UINT256 },
            { name: 'effectiveBorrowAPY', type: ABIDataTypes.UINT256 },
            { name: 'discountBps', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getRiskStatus',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'collateralValue', type: ABIDataTypes.UINT256 },
            { name: 'borrowValue', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'loanToValueRatio', type: ABIDataTypes.UINT256 },
            { name: 'riskStatus', type: ABIDataTypes.UINT256 },
            { name: 'safeMaxBorrow', type: ABIDataTypes.UINT256 },
            { name: 'warningMaxBorrow', type: ABIDataTypes.UINT256 },
            { name: 'liquidationCollatValue', type: ABIDataTypes.UINT256 },
            { name: 'distanceToLiquidationBps', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_previewRisk2',
        inputs: [
            { name: 'action', type: ABIDataTypes.UINT8 },
            { name: 'token', type: ABIDataTypes.UINT8 },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [
            { name: 'currentRiskStatus', type: ABIDataTypes.UINT256 },
            { name: 'newRiskStatus', type: ABIDataTypes.UINT256 },
            { name: 'currentHF', type: ABIDataTypes.UINT256 },
            { name: 'newHF', type: ABIDataTypes.UINT256 },
            { name: 'currentLTV', type: ABIDataTypes.UINT256 },
            { name: 'newLTV', type: ABIDataTypes.UINT256 },
            { name: 'currentBorrowValue', type: ABIDataTypes.UINT256 },
            { name: 'newBorrowValue', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getRiskParameters',
        inputs: [],
        outputs: [
            { name: 'liquidationThreshold', type: ABIDataTypes.UINT256 },
            { name: 'hfLiquidationFloor', type: ABIDataTypes.UINT256 },
            { name: 'hfSafeThreshold', type: ABIDataTypes.UINT256 },
            { name: 'liquidationBonus', type: ABIDataTypes.UINT256 },
            { name: 'maxLiquidationPct', type: ABIDataTypes.UINT256 },
            { name: 'collateralRatioBps', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getVault',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'totalCollateralValue', type: ABIDataTypes.UINT256 },
            { name: 'totalBorrowValue', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'loanToValueRatio', type: ABIDataTypes.UINT256 },
            { name: 'liquidationThreshold', type: ABIDataTypes.UINT256 },
            { name: 'liquidationHFThreshold', type: ABIDataTypes.UINT256 },
            { name: 'availableCredit', type: ABIDataTypes.UINT256 },
            { name: 'isLiquidatable', type: ABIDataTypes.UINT256 },
            { name: 'btcCollateralBalance', type: ABIDataTypes.UINT256 },
            { name: 'motoCollateralBalance', type: ABIDataTypes.UINT256 },
            { name: 'pillCollateralBalance', type: ABIDataTypes.UINT256 },
            { name: 'btcDebtBalance', type: ABIDataTypes.UINT256 },
            { name: 'motoDebtBalance', type: ABIDataTypes.UINT256 },
            { name: 'pillDebtBalance', type: ABIDataTypes.UINT256 },
            { name: 'btcCollateralEnabled', type: ABIDataTypes.UINT256 },
            { name: 'motoCollateralEnabled', type: ABIDataTypes.UINT256 },
            { name: 'pillCollateralEnabled', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_stakePill',
        inputs: [{ name: 'amount', type: ABIDataTypes.UINT256 }],
        outputs: [
            { name: 'totalStaked', type: ABIDataTypes.UINT256 },
            { name: 'protectionActive', type: ABIDataTypes.UINT256 },
            { name: 'liqThreshold', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_unstakePill',
        inputs: [{ name: 'amount', type: ABIDataTypes.UINT256 }],
        outputs: [
            { name: 'totalStaked', type: ABIDataTypes.UINT256 },
            { name: 'protectionActive', type: ABIDataTypes.UINT256 },
            { name: 'liqThreshold', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getPillProtection',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'pillStaked', type: ABIDataTypes.UINT256 },
            { name: 'protectionActive', type: ABIDataTypes.UINT256 },
            { name: 'liqThreshold', type: ABIDataTypes.UINT256 },
            { name: 'minStakeRequired', type: ABIDataTypes.UINT256 },
            { name: 'pillToActivate', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_openLoop',
        inputs: [{ name: 'loopLevel', type: ABIDataTypes.UINT8 }],
        outputs: [
            { name: 'loopLevel', type: ABIDataTypes.UINT8 },
            { name: 'initialBtcDeposit', type: ABIDataTypes.UINT256 },
            { name: 'motoBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'totalBtcExposure', type: ABIDataTypes.UINT256 },
            { name: 'totalCollatSats', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
            { name: 'riskStatus', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_closeLoop',
        inputs: [],
        outputs: [
            { name: 'wasActive', type: ABIDataTypes.UINT256 },
            { name: 'motoDebt', type: ABIDataTypes.UINT256 },
            { name: 'btcBalance', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_getLoopMetrics',
        inputs: [{ name: 'user', type: ABIDataTypes.ADDRESS }],
        outputs: [
            { name: 'loopLevel', type: ABIDataTypes.UINT8 },
            { name: 'isActive', type: ABIDataTypes.UINT256 },
            { name: 'initialBtcDeposit', type: ABIDataTypes.UINT256 },
            { name: 'currentBtcBalance', type: ABIDataTypes.UINT256 },
            { name: 'loopedBtcAdded', type: ABIDataTypes.UINT256 },
            { name: 'motoBorrowed', type: ABIDataTypes.UINT256 },
            { name: 'totalCollatSats', type: ABIDataTypes.UINT256 },
            { name: 'healthFactor', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: '_previewLoop',
        inputs: [{ name: 'loopLevel', type: ABIDataTypes.UINT8 }],
        outputs: [
            { name: 'projectedMotoToBorrow', type: ABIDataTypes.UINT256 },
            { name: 'projectedBtcToAdd', type: ABIDataTypes.UINT256 },
            { name: 'projectedTotalCollatSats', type: ABIDataTypes.UINT256 },
            { name: 'projectedBorrowSats', type: ABIDataTypes.UINT256 },
            { name: 'projectedHF', type: ABIDataTypes.UINT256 },
            { name: 'projectedRiskStatus', type: ABIDataTypes.UINT256 },
            { name: 'isSafe', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Function,
    },
    ...LendBTCEvents,
    ...OP_NET_ABI,
];

export default LendBTCAbi;
